name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    strategy: { matrix: { os: [ ubuntu-latest, macos-latest ] } }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          root: __test__
      - run: (cd __test__; . run.sh)
      - run: test "${{ steps.action.outputs.cache-hit }}" != true

  cached:
    needs: initial
    strategy: { matrix: { os: [ ubuntu-latest, macos-latest ] } }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          root: __test__
      - run: (cd __test__; . run.sh)
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
  no-root:
    needs: cached
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
      - run: (cd __test__; . run.sh)
      - run: echo "cache-hit=\"${{ steps.action.outputs.cache-hit }}\""
  no-cache:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: no
          root: __test__
      - run: (cd __test__; . run.sh)
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  key:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          root: __test__
          key: v2
      - run: (cd __test__; . run.sh)
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
